### ISSUE TITLE
Upgrade disgord version

### ISSUE THREAD

**Issue by andersfylling** [polaron/aurora#2]
Hi, just notifying that Discord decided to do a breaking change to their API that takes place within less than a month. Because of this I suggest upgrading to v0.11 (the latest release) such that your application does not cease to function. Sorry about the inconvenience!

Source: https://github.com/discordapp/discord-api-docs/pull/967

**Comment by andersfylling** [comment]
I see you are using v0.9, so I highly recommend reading the docs/CHANGELOG-v0.10 as many functions have been renamed to provide a more consistent interface.

**Comment by pazuzu156** [comment]
@andersfylling I've forked this project, and it's updated to work with the latest stable release of disgord ;)

**Comment by andersfylling** [comment]
I upgraded the disgord wiki to refer to your projects instead. this seems to be dead(?).

**Comment by pazuzu156** [comment]
No clue, I'll continue working on my fork though, making pull requests ofc to this repo.
